#!/usr/local/bin/perl
# -*- perl -*-

# Copyright (c) 2014
# Author: Jeff Weisberg <jaw @ solvemedia.com>
# Created: 2014-Mar-13 15:32 (EDT)
# Function: 

use lib '/home/adcopy/lib';
use AC::Protocol;
use AC::Dumper;
use AC::Misc;
use Socket;

require 'AC/protobuf/scrible.pl';

use strict;


my $req = AC::Protocol->encode_request( {
    type        => 'scribl_get',
    msgidno     => $$,
    want_reply  => 1,
}, {
    filename	=> 'foobar',
} );


my $res = AC::Protocol->send_request( inet_aton("127.0.0.1"), 3509, $req,
                                      sub{ print STDERR "@_\n" } );

if( $res && $res->{data} ){
    $res->{data} = AC::Protocol->decode_reply( $res );
}


print STDERR "result ", dumper($res), "\n";
