#!/usr/local/bin/perl
# -*- perl -*-

# Copyright (c) 2014
# Author: Jeff Weisberg <jaw @ solvemedia.com>
# Created: 2014-Mar-28 13:15 (EDT)
# Function: 

print <<'EOPLAN';
task 4
map mrm/dev@whitefish.ccsphl 20000000 4
file data/0732_prod_54zF.rpJrdtCe8NI_.gz
file data/0902_prod_S4zF.uZ0rdedzcP8_.gz
file data/1212_prod_go7F.sC-rdtCdMMD_.gz
file data/3140_prod_OYTF.tt-rdedCMNU_.gz
map mrm/dev@whitefish.ccsphl 20000000 4
file data/0732_prod_54zF.rpJrdtCe8NI_.gz
file data/0902_prod_S4zF.uZ0rdedzcP8_.gz
file data/1212_prod_go7F.sC-rdtCdMMD_.gz
file data/3140_prod_OYTF.tt-rdedCMNU_.gz
map mrm/dev@whitefish.ccsphl 20000000 4
file data/0732_prod_54zF.rpJrdtCe8NI_.gz
file data/0902_prod_S4zF.uZ0rdedzcP8_.gz
file data/1212_prod_go7F.sC-rdtCdMMD_.gz
file data/3140_prod_OYTF.tt-rdedCMNU_.gz
map mrm/dev@whitefish.ccsphl 20000000 4
file data/0732_prod_54zF.rpJrdtCe8NI_.gz
file data/0902_prod_S4zF.uZ0rdedzcP8_.gz
file data/1212_prod_go7F.sC-rdtCdMMD_.gz
file data/3140_prod_OYTF.tt-rdedCMNU_.gz
EOPLAN
;

